name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  chk_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v15
        id: verify-changed-files
      
      - name: List all changed files tracked and untracked files
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
      
  check_modified_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print variable values
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
      - name: Get list of modified files
        id: modified_files
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "files<<$EOF" >> $GITHUB_OUTPUT
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Check if readme.md was modified
        run: |
          if [[ "${{ steps.modified_files.outputs.files }}" == "README.md" ]]; then
            echo "readme.md was modified"
          else
            echo "readme.md was not modified"
          fi
  print_comment:
    runs-on: ubuntu-latest        
    steps:
    - name: Get pull request comments
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        description="${{ github.event.pull_request.body }}"
        echo "$description"
