name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  check_modified_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print variable values
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
      - name: Get list of modified files
        id: modified_files
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')
          echo "files=$files" >> $GITHUB_OUTPUT
          echo "Modified files: $files
      - name: Check if readme.md was modified
        run: |
          if [[ "${{ steps.modified_files.outputs.files }}" == "README.md" ]]; then
            echo "readme.md was modified"
          else
            echo "readme.md was not modified"
          fi
  print_comment:
    runs-on: ubuntu-latest        
    steps:
    - name: Get pull request comments
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        description="${{ github.event.pull_request.body }}"
        echo "$description"
