name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  check_modified_files:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{steps.validate-only-readme-change.outputs.valid}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate changes
        id: validate-only-readme-change
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Modified files: $files"

          files=$(echo "$files" | sed -E 's#\.github/workflows/.*##g')

          #files_str=$(echo "$files" | tr -d '\n')

          #echo "str files: $files_str"
          if [[ "$files" == "README.md" ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "readme.md was modified"
          fi
  print_comment:
    runs-on: ubuntu-latest
    needs:
      - check_modified_files
    if:  needs.check_modified_files.outputs.valid == 'true'       
    steps:
    - name: Get pull request comments
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        description="${{ needs.check_modified_files.outputs.valid }}"
        echo "$description"
