name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  check_modified_files:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{steps.chk123.outputs.valid}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get list of modified files
        id: modified_files
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')
          echo "files=$files" >> $GITHUB_OUTPUT
      - name: Check if readme.md was modified
        id: chk123
        run: |
          if [[ "${{ steps.modified_files.outputs.files }}" == "README.md" ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            echo "readme.md was modified"
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "readme.md was not modified"
          fi
  print_comment:
    runs-on: ubuntu-latest  
    needs:
      - check_modified_files
   # if: ${{ needs.check_modified_files.outputs.valid == 'true' }}      
    steps:
    - name: Get pull request comments
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        description="${{ needs.check_modified_files.outputs.valid }}"
        echo "$description"
